import { useQuery } from '@tanstack/react-query'
import { universityApi } from '@/api/endpoints'
import Spinner    from '@/components/common/Spinner'
import EmptyState from '@/components/common/EmptyState'
import { fmt }    from '@/utils/formatDate'
import { BarChart2, FileText, Download } from 'lucide-react'

const reportTypeLabel: Record<string, string> = {
  LOGBOOK_SUMMARY:       'Logbook Summary',
  EVALUATION_REPORT:     'Evaluation Report',
  PLACEMENT_ANALYTICS:   'Placement Analytics',
  INSTITUTIONAL_REPORT:  'Institutional Report',
  COMPLETION_CERTIFICATE:'Completion Certificate',
}

export default function UniversityReports() {
  const { data, isLoading } = useQuery({
    queryKey: ['university-reports'],
    queryFn:  universityApi.getReports,
  })

  const reports: any[] = data?.data?.data ?? []

  if (isLoading) return <div className="flex items-center justify-center h-64"><Spinner size="lg" /></div>

  return (
    <div>
      <div className="page-header">
        <div>
          <h1>Reports</h1>
          <p className="text-sm text-gray-500 mt-1">Generated reports for your institution</p>
        </div>
      </div>

      {/* Info banner */}
      <div className="bg-brand-50 border border-brand-200 rounded-xl p-4 mb-6">
        <p className="text-sm text-brand-800">
          <strong>Reports</strong> are generated by the system administrator. Contact your admin to request
          institutional reports, placement analytics, or completion certificates for your students.
        </p>
      </div>

      {reports.length === 0 ? (
        <EmptyState
          icon={<BarChart2 size={48} />}
          title="No reports yet"
          description="Reports generated for your institution will appear here."
        />
      ) : (
        <div className="space-y-3">
          {reports.map((r) => (
            <div key={r.id} className="card p-5 flex items-center justify-between gap-4">
              <div className="flex items-center gap-4">
                <div className="p-2.5 rounded-xl bg-brand-50 text-brand-600">
                  <FileText size={20} />
                </div>
                <div>
                  <p className="font-semibold text-sm text-gray-900">{r.title}</p>
                  <p className="text-xs text-gray-400 mt-0.5">
                    {reportTypeLabel[r.type] ?? r.type} · Generated {fmt(r.generatedAt)}
                  </p>
                  {r.description && <p className="text-xs text-gray-500 mt-1">{r.description}</p>}
                </div>
              </div>
              {r.fileUrl && (
                <a
                  href={r.fileUrl}
                  target="_blank"
                  rel="noreferrer"
                  className="btn-secondary text-xs py-1.5 flex-shrink-0"
                >
                  <Download size={13} /> Download
                </a>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
