import { useState } from 'react'
import { useQuery, useMutation } from '@tanstack/react-query'
import { reportApi } from '@/api/endpoints'
import Spinner    from '@/components/common/Spinner'
import EmptyState from '@/components/common/EmptyState'
import { fmt }    from '@/utils/formatDate'
import {
  FileText, Download, BarChart2,
  BookOpen, Award, RefreshCw,
} from 'lucide-react'
import toast from 'react-hot-toast'

interface Report {
  id:          string
  type:        string
  title:       string
  fileUrl:     string | null
  generatedAt: string
}

const typeIcon: Record<string, React.ReactNode> = {
  LOGBOOK_SUMMARY:       <BookOpen  size={18} />,
  EVALUATION_REPORT:     <BarChart2 size={18} />,
  COMPLETION_CERTIFICATE:<Award     size={18} />,
}

const typeBadge: Record<string, string> = {
  LOGBOOK_SUMMARY:       'badge-blue',
  EVALUATION_REPORT:     'badge-purple',
  COMPLETION_CERTIFICATE:'badge-green',
}

const typeLabel: Record<string, string> = {
  LOGBOOK_SUMMARY:        'Logbook summary',
  EVALUATION_REPORT:      'Evaluation report',
  COMPLETION_CERTIFICATE: 'Completion certificate',
}

export default function StudentReports() {
  const [generating, setGenerating] = useState<string | null>(null)

  const { data, isLoading, refetch } = useQuery({
    queryKey: ['my-reports'],
    queryFn:  reportApi.myReports,
  })

  const reports: Report[] = data?.data?.data ?? []

  const logbookMutation = useMutation({
    mutationFn: reportApi.generateLogbook,
    onMutate:   () => setGenerating('logbook'),
    onSuccess: () => {
      toast.success('Logbook PDF generated!')
      refetch()
    },
    onError: () => toast.error('Failed to generate logbook PDF'),
    onSettled:  () => setGenerating(null),
  })

  const reportActions = [
    {
      key:         'logbook',
      title:       'Logbook summary PDF',
      description: 'Generate a PDF of all your logbook entries for this internship.',
      icon:        <BookOpen  size={20} className="text-blue-500" />,
      bg:          'bg-blue-50 border-blue-200',
      onGenerate:  () => logbookMutation.mutate(),
      loading:     generating === 'logbook',
    },
  ]

  if (isLoading) return <div className="flex items-center justify-center h-64"><Spinner size="lg" /></div>

  return (
    <div>
      <div className="page-header">
        <div>
          <h1>Reports</h1>
          <p className="text-sm text-gray-500 mt-1">Generate and download your internship documents</p>
        </div>
      </div>

      {/* Generate actions */}
      <h2 className="section-title">Generate reports</h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mb-8">
        {reportActions.map((action) => (
          <div key={action.key} className={`card p-5 border ${action.bg}`}>
            <div className="flex items-start justify-between mb-3">
              <div className="p-2 rounded-lg bg-white border border-white/50 shadow-sm">
                {action.icon}
              </div>
            </div>
            <h3 className="font-semibold text-sm text-gray-900 mb-1">{action.title}</h3>
            <p className="text-xs text-gray-500 mb-4 leading-relaxed">{action.description}</p>
            <button
              onClick={action.onGenerate}
              disabled={action.loading}
              className="btn-primary w-full justify-center text-xs py-1.5"
            >
              {action.loading
                ? <><RefreshCw size={13} className="animate-spin" /> Generating…</>
                : <><FileText size={13} /> Generate</>
              }
            </button>
          </div>
        ))}

        {/* Info card for evaluation reports */}
        <div className="card p-5 border bg-purple-50 border-purple-200">
          <div className="flex items-start justify-between mb-3">
            <div className="p-2 rounded-lg bg-white border shadow-sm">
              <BarChart2 size={20} className="text-purple-500" />
            </div>
          </div>
          <h3 className="font-semibold text-sm text-gray-900 mb-1">Evaluation report PDF</h3>
          <p className="text-xs text-gray-500 mb-4 leading-relaxed">
            Generated by your academic supervisor after your evaluation is approved.
          </p>
          <div className="flex items-center gap-2 text-xs text-purple-600">
            <RefreshCw size={11} />
            <span>Auto-generated when approved</span>
          </div>
        </div>

        {/* Certificate info */}
        <div className="card p-5 border bg-green-50 border-green-200">
          <div className="flex items-start justify-between mb-3">
            <div className="p-2 rounded-lg bg-white border shadow-sm">
              <Award size={20} className="text-green-500" />
            </div>
          </div>
          <h3 className="font-semibold text-sm text-gray-900 mb-1">Completion certificate</h3>
          <p className="text-xs text-gray-500 mb-4 leading-relaxed">
            Issued by your institution once your internship is fully approved and signed off.
          </p>
          <div className="flex items-center gap-2 text-xs text-green-600">
            <RefreshCw size={11} />
            <span>Issued after full sign-off</span>
          </div>
        </div>
      </div>

      {/* Previous reports */}
      <h2 className="section-title">Generated reports</h2>

      {reports.length === 0 ? (
        <EmptyState
          icon={<FileText size={48} />}
          title="No reports yet"
          description="Use the actions above to generate your first report."
        />
      ) : (
        <div className="card overflow-hidden">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-gray-50 border-b border-gray-100">
                <th className="text-left px-5 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide">Type</th>
                <th className="text-left px-5 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide">Title</th>
                <th className="text-left px-5 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide">Generated</th>
                <th className="text-right px-5 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {reports.map((report) => (
                <tr key={report.id} className="hover:bg-gray-50 transition-colors">
                  <td className="px-5 py-3">
                    <div className="flex items-center gap-2">
                      <span className="text-gray-400">
                        {typeIcon[report.type] ?? <FileText size={18} />}
                      </span>
                      <span className={typeBadge[report.type] ?? 'badge-gray'}>
                        {typeLabel[report.type] ?? report.type}
                      </span>
                    </div>
                  </td>
                  <td className="px-5 py-3 text-gray-700 max-w-xs truncate">{report.title}</td>
                  <td className="px-5 py-3 text-gray-400 text-xs">{fmt(report.generatedAt)}</td>
                  <td className="px-5 py-3 text-right">
                    {report.fileUrl ? (
                      <a
                        href={report.fileUrl}
                        target="_blank"
                        rel="noreferrer"
                        className="inline-flex items-center gap-1.5 text-xs text-brand-600 hover:text-brand-700 font-medium"
                      >
                        <Download size={13} /> Download
                      </a>
                    ) : (
                      <span className="text-xs text-gray-300">Unavailable</span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}
