import { Request, Response, NextFunction } from 'express'
import * as reportService from '@/services/report.service'
import { sendSuccess } from '@/utils/apiResponse'
import { prisma } from '@/config/db'

// Generate a logbook summary PDF for a student
export const generateLogbookPdf = async (
  req:  Request,
  res:  Response,
  next: NextFunction
): Promise<void> => {
  try {
    // Admins and supervisors can pass a studentId;
    // students always generate their own report
    const rawId = req.params.studentId ?? req.user!.id
    const targetStudentId = Array.isArray(rawId) ? rawId[0] : rawId

    // Resolve to StudentProfile.id if what we have is a User.id
    let profileId = targetStudentId
    const profile = await prisma.studentProfile.findUnique({ where: { userId: targetStudentId } })
    if (profile) profileId = profile.id

    const fileUrl = await reportService.generateLogbookPdf(profileId, req.user!.id)
    sendSuccess(res, { fileUrl }, 'Logbook PDF generated')
  } catch (err) { next(err) }
}

// Generate an evaluation report PDF for an enrollment
export const generateEvaluationPdf = async (
  req:  Request,
  res:  Response,
  next: NextFunction
): Promise<void> => {
  try {
    const enrollmentId = Array.isArray(req.params.enrollmentId)
      ? req.params.enrollmentId[0]
      : req.params.enrollmentId
    const fileUrl = await reportService.generateEvaluationPdf(enrollmentId, req.user!.id)
    sendSuccess(res, { fileUrl }, 'Evaluation report PDF generated')
  } catch (err) { next(err) }
}

// Generate a completion certificate PDF for an enrollment
export const generateCertificate = async (
  req:  Request,
  res:  Response,
  next: NextFunction
): Promise<void> => {
  try {
    const enrollmentId = Array.isArray(req.params.enrollmentId)
      ? req.params.enrollmentId[0]
      : req.params.enrollmentId
    const fileUrl = await reportService.generateCertificate(enrollmentId, req.user!.id)
    sendSuccess(res, { fileUrl }, 'Certificate generated')
  } catch (err) { next(err) }
}

// Generate an institutional Excel report (Admin only)
export const generateInstitutionalExcel = async (
  req:  Request,
  res:  Response,
  next: NextFunction
): Promise<void> => {
  try {
    const fileUrl = await reportService.generateInstitutionalExcel(
      req.user!.id,
      {
        department: req.query.department as string | undefined,
        year:       req.query.year ? parseInt(req.query.year as string) : undefined,
      }
    )
    sendSuccess(res, { fileUrl }, 'Institutional report generated')
  } catch (err) { next(err) }
}

// Get placement analytics JSON (for dashboard charts)
export const getAnalytics = async (
  _req: Request,
  res:  Response,
  next: NextFunction
): Promise<void> => {
  try {
    const data = await reportService.getPlacementAnalytics()
    sendSuccess(res, data)
  } catch (err) { next(err) }
}

// List all reports generated by the current user
export const listMyReports = async (
  req:  Request,
  res:  Response,
  next: NextFunction
): Promise<void> => {
  try {
    const reports = await prisma.report.findMany({
      where:   { generatedById: req.user!.id },
      orderBy: { generatedAt: 'desc' },
    })
    sendSuccess(res, reports)
  } catch (err) { next(err) }
}

// List all reports (Admin only)
export const listAllReports = async (
  _req: Request,
  res:  Response,
  next: NextFunction
): Promise<void> => {
  try {
    const reports = await prisma.report.findMany({
      orderBy: { generatedAt: 'desc' },
      take:    200,
    })
    sendSuccess(res, reports)
  } catch (err) { next(err) }
}
