import 'reflect-metadata'
import {
  Controller,
  Get,
  Path,
  Post,
  Query,
  Request,
  Route,
  Security,
  Tags,
} from 'tsoa'
import type { Request as ExpressRequest } from 'express'
import * as reportService from '@/services/report.service'
import { prisma } from '@/config/db'
import type { MessageResponse } from './auth.controller'

@Route('api/reports')
@Tags('Reports')
@Security('bearerAuth')
export class ReportController extends Controller {

  /** List all reports generated by the authenticated user */
  @Get('/')
  public async listMyReports(@Request() req: ExpressRequest): Promise<MessageResponse> {
    const reports = await prisma.report.findMany({
      where:   { generatedById: req.user!.id },
      orderBy: { generatedAt: 'desc' },
    })
    return { success: true, message: 'Success', data: reports }
  }

  /** List all reports in the system (Admin only) */
  @Get('all')
  public async listAllReports(): Promise<MessageResponse> {
    const reports = await prisma.report.findMany({
      orderBy: { generatedAt: 'desc' },
      take:    200,
    })
    return { success: true, message: 'Success', data: reports }
  }

  /**
   * Get placement analytics data for dashboard charts.
   * Includes enrollment trends, application statuses, and average evaluation scores.
   */
  @Get('analytics')
  public async getAnalytics(): Promise<MessageResponse> {
    const data = await reportService.getPlacementAnalytics()
    return { success: true, message: 'Success', data }
  }

  /**
   * Generate a logbook summary PDF for the authenticated student.
   * Returns a Cloudinary URL to the generated PDF.
   */
  @Post('logbook/me')
  public async generateMyLogbookPdf(@Request() req: ExpressRequest): Promise<MessageResponse> {
    const profile = await prisma.studentProfile.findUnique({ where: { userId: req.user!.id } })
    if (!profile) { this.setStatus(404); return { success: false, message: 'Student profile not found' } }
    const fileUrl = await reportService.generateLogbookPdf(profile.id, req.user!.id)
    return { success: true, message: 'Logbook PDF generated', data: { fileUrl } }
  }

  /**
   * Generate a logbook summary PDF for a specific student (Supervisor / Admin).
   * @param studentId StudentProfile UUID
   */
  @Post('logbook/{studentId}')
  public async generateLogbookPdf(
    @Path() studentId: string,
    @Request() req: ExpressRequest,
  ): Promise<MessageResponse> {
    const fileUrl = await reportService.generateLogbookPdf(studentId, req.user!.id)
    return { success: true, message: 'Logbook PDF generated', data: { fileUrl } }
  }

  /**
   * Generate an evaluation report PDF for an enrollment.
   * @param enrollmentId InternshipEnrollment UUID
   */
  @Post('evaluation/{enrollmentId}')
  public async generateEvaluationPdf(
    @Path() enrollmentId: string,
    @Request() req: ExpressRequest,
  ): Promise<MessageResponse> {
    const fileUrl = await reportService.generateEvaluationPdf(enrollmentId, req.user!.id)
    return { success: true, message: 'Evaluation report PDF generated', data: { fileUrl } }
  }

  /**
   * Generate a completion certificate PDF for an enrollment.
   * @param enrollmentId InternshipEnrollment UUID
   */
  @Post('certificate/{enrollmentId}')
  public async generateCertificate(
    @Path() enrollmentId: string,
    @Request() req: ExpressRequest,
  ): Promise<MessageResponse> {
    const fileUrl = await reportService.generateCertificate(enrollmentId, req.user!.id)
    return { success: true, message: 'Certificate generated', data: { fileUrl } }
  }

  /**
   * Generate an institutional analytics Excel report (Admin only).
   * Returns a Cloudinary URL to the generated .xlsx file.
   */
  @Post('institutional')
  public async generateInstitutionalExcel(
    @Request() req: ExpressRequest,
    @Query() department?: string,
    @Query() year?:       number,
  ): Promise<MessageResponse> {
    const fileUrl = await reportService.generateInstitutionalExcel(
      req.user!.id,
      { department, year },
    )
    return { success: true, message: 'Institutional report generated', data: { fileUrl } }
  }
}
