import { Router, Request, Response, NextFunction } from 'express'
import { Role } from '@prisma/client'
import { protect } from '@/middleware/auth.middleware'
import { authorize } from '@/middleware/rbac.middleware'
import { prisma } from '@/config/db'
import { sendSuccess } from '@/utils/apiResponse'

const router = Router()

// List reports generated by or accessible to the current user
router.get('/', protect, async (req: Request, res: Response, next: NextFunction) => {
  try {
    const reports = await prisma.report.findMany({
      where:   { generatedById: req.user!.id },
      orderBy: { generatedAt: 'desc' },
    })
    sendSuccess(res, reports)
  } catch (err) { next(err) }
})

// Admin — all reports
router.get('/all', protect, authorize(Role.ADMIN), async (req: Request, res: Response, next: NextFunction) => {
  try {
    const reports = await prisma.report.findMany({ orderBy: { generatedAt: 'desc' }, take: 100 })
    sendSuccess(res, reports)
  } catch (err) { next(err) }
})

// Analytics summary for admin dashboard
router.get('/analytics/summary', protect, authorize(Role.ADMIN), async (_req: Request, res: Response, next: NextFunction) => {
  try {
    const [
      totalStudents, totalCompanies, totalInternships,
      totalApplications, totalEnrollments, openInternships,
    ] = await Promise.all([
      prisma.studentProfile.count(),
      prisma.companyProfile.count(),
      prisma.internship.count(),
      prisma.application.count(),
      prisma.internshipEnrollment.count(),
      prisma.internship.count({ where: { status: 'OPEN' } }),
    ])

    sendSuccess(res, {
      totalStudents,
      totalCompanies,
      totalInternships,
      totalApplications,
      totalEnrollments,
      openInternships,
    })
  } catch (err) { next(err) }
})

export default router
